

server:
  port: 8080
  servlet:
    context-path: /jete


spring:
  datasource:
    url: jdbc:mysql://192.168.18.2:3306/jete?characterEncoding=utf8
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'